language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .[test]
  - pip install codecov
# command to run tests
script: pytest --cov=./dvb test
after_success:
  - codecov
